baseURL = "http://www.thoughtart.in/"
languageCode = "en-us"
title = "Thought Thou Art"
theme = "courseware"
ignoreFiles = [ "\\.pxm$", "\\.mindnode$", "raw" ]
googleAnalytics = "UA-161383666-1"
[params]
  meta_pages_left = ["About"]
  meta_pages_right = ["Terms", "Follow", "Contact"]

  # (Optional, default none) Set the path to a logo for the site. If the logo is
  # /static/logo.png then the path would be logo.png
  SiteLogo = 'logo.png'

  custom_css = ["css/bar.css"]

  twitterURL = "https://twitter.com/thou_thought"
  facebookURL = "https://facebook.com/ThoughtThouArt"
  githubURL = "https://github.com/anandjanki/thoughtart"

